//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmesagasDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategoris
    {
        public int id { get; set; }
        public string KategoriAdi { get; set; }
        public string KategoriAciklama { get; set; }
    
        public virtual Uruns Uruns { get; set; }
    }
}
