//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmesagasDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmesagasEntities1 : DbContext
    {
        public EmesagasEntities1()
            : base("name=EmesagasEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Fotografs> Fotografs { get; set; }
        public virtual DbSet<Kategoris> Kategoris { get; set; }
        public virtual DbSet<SiparisDetays> SiparisDetays { get; set; }
        public virtual DbSet<Sipariss> Sipariss { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Uruns> Uruns { get; set; }
        public virtual DbSet<UyeIpAdreslers> UyeIpAdreslers { get; set; }
        public virtual DbSet<Uyes> Uyes { get; set; }
    }
}
