//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmesagasDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sipariss
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sipariss()
        {
            this.SiparisDetays = new HashSet<SiparisDetays>();
        }
    
        public int id { get; set; }
        public int SiparisUyeId { get; set; }
        public decimal SiparisTutari { get; set; }
        public string KargoAlicisi { get; set; }
        public string KargoAdresi { get; set; }
        public int KargoSehirId { get; set; }
        public string KargoTelefon { get; set; }
        public int KargoYontemiId { get; set; }
        public int OdemeYontemiId { get; set; }
        public System.DateTime SiparisTarih { get; set; }
        public System.DateTime KargolanmaTarih { get; set; }
        public string KargoTakipNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetays> SiparisDetays { get; set; }
        public virtual Uyes Uyes { get; set; }
    }
}
