//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmesagasDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisDetays
    {
        public int id { get; set; }
        public int DetaySiparisId { get; set; }
        public int DetayUrunId { get; set; }
        public decimal DetayFiyat { get; set; }
        public short DetayAdet { get; set; }
    
        public virtual Sipariss Sipariss { get; set; }
        public virtual Uruns Uruns { get; set; }
    }
}
