//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmesagasDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UyeIpAdreslers
    {
        public int id { get; set; }
        public int UyeId { get; set; }
        public string IpNo { get; set; }
    
        public virtual Uyes Uyes { get; set; }
        public virtual Uyes Uyes1 { get; set; }
    }
}
